use employeedb;

CREATE TABLE `TEAM_INFO` (
    `TEAM_CODE` INT AUTO_INCREMENT COMMENT '소속코드',
    `TEAM_NAME` VARCHAR(100) COMMENT '소속명',
    `TEAM_DETAIL` VARCHAR(500) COMMENT '소속상세정보',
    `USE_YN` CHAR(2) NOT NULL DEFAULT 'Y' COMMENT '.사용여부',
    PRIMARY KEY (`TEAM_CODE`),
    CHECK (USE_YN IN ('Y', 'N')),
) ENGINE=INNODB COMMENT='소속정보';


CREATE TABLE `MEMBER_INFO` (
    `MEMBER_CODE` INT AUTO_INCREMENT COMMENT '회원코드',
    `MEMBER_NAME` VARCHAR(70) NOT NULL COMMENT '회원이름',
    `BIRTH` DATE COMMENT '생년월일',
    `DIVISION_CODE` CHAR(2) COMMENT '구분코드',
    `DETAIL_INFO` VARCHAR(500) COMMENT '상세정보',
    `CONTACT` VARCHAR(50) NOT NULL COMMENT '연락처',
    `TEAM_CODE` INT NOT NULL COMMENT '소속코드',
    `ACTIVE_STATUS` CHAR(2) NOT NULL DEFAULT 'Y' COMMENT '활동상태',
    PRIMARY KEY (`MEMBER_CODE`),
    FOREIGN KEY (`TEAM_CODE`) REFERENCES `TEAM_INFO`(`TEAM_CODE`),
    CHECK (ACTIVE_STATUS IN ('Y', 'N', 'H'))
) ENGINE=INNODB COMMENT='회원정보';